language: node
sudo: false
script:
  - node createjson.js
deploy:
  provider: gcs
  access_key_id: $GCS_ACCESS_KEY_ID
  secret_access_key: $GCS_SECRET_ACCESS_KEY
  bucket: "tutos"
  skip_cleanup: true
  acl: public-read
  local-dir: _posts
  on:
    branch: master
