os: linux
dist: xenial

language: node_js
node_js:
  - "8"

install:
  - yarn install

before_script:
  - node createjson.js

script:
  - yarn lint
  - yarn test
  - yarn build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_1d9c94ec092f_key -iv $encrypted_1d9c94ec092f_iv -in codelabs-1ddb09746a38.json.enc -out codelabs-1ddb09746a38.json -d

deploy:
  - provider: gcs
    access_key_id: "$GCS_ACCESS_KEY_ID"
    secret_access_key: "$GCS_SECRET_ACCESS_KEY"
    bucket: tutos
    skip_cleanup: true
    acl: public-read
    cache_control: public,max-age=60
    local_dir: _posts
    on:
      branch: master
  - provider: gae
    keyfile: codelabs-1ddb09746a38.json
    project: codelabs-179614
    skip_cleanup: true
    on:
      branch: master

after_deploy:
  - node index_algolia.js

notifications:
  slack:
    if: branch = master
    rooms:
      - secure: "$SLACK_SECURE"
    template:
      - "Nouvelle version de codelabs en prod => %{message}"
    on_pull_requests: false
    on_success: always
    on_failure: never
