version: 2
workflows:
  version: 2
  test:
    jobs:
      - node8
      - node9
jobs:
  node8: &build-template
    docker:
      - image: circleci/node:8
    working_directory: ~/codelabs
    steps:
      - checkout
      - run:
          name: install yarn
          command: yarn install
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test

  node9:
    <<: *build-template
    docker:
      - image: circleci/node:9
        environment:
          NODE_VERSION: 9
