version: 2
jobs:
  build:
    working_directory: ~/codelabs
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: install yarn
          command: 'yarn install'
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test

  build-node9:
    working_directory: ~/codelabs
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: install yarn
          command: 'yarn install'
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
