version: 2
workflows:
  version: 2
  test:
    jobs:
      - node8
      - node9
jobs:
  node8: &build-template
    working_directory: ~/codelabs
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          name: restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: install yarn
          command: 'yarn install'
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
      - save_cache:
          name: save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  node9:
    <<: *build-template
    docker:
      - image: circleci/node:9
